# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107d9616d4889662cc8de51f3271d190f418f133c4d7b2e973a5a67f4f12b5def1cd2a3d2e8b1da53c79e3bfccf0198b2265afbdfb85d1e015e7ddc4555364e8

test:
  secret_key_base: b7baec2d3a7def89fb21dfc1cb384b9b10806331ea0dde4efb282876ea98a005b72f21ad4a91a7db2a6f071383a4e6d238b0a8644498c9fab64f563268d9424c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 107d9616d4889662cc8de51f3271d190f418f133c4d7b2e973a5a67f4f12b5def1cd2a3d2e8b1da53c79e3bfccf0198b2265afbdfb85d1e015e7ddc4555364e8
